<?php
/**
 * @contains EnhancedLinkWidget.php
 * User: goce
 * Date: 1/24/18
 * Time: 11:28 AM
 */

namespace Drupal\qtx_embed_promo\Plugin\Field\FieldWidget;

use Drupal\Core\Annotation\Translation;
use Drupal\Core\Field\Annotation\FieldWidget;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\link\Plugin\Field\FieldWidget\LinkWidget;


/**
 * Extends the default "Link" plugin widget to provide maximum character length.
 *
 * @FieldWidget(
 *   id = "link_extended_default",
 *   label = @Translation("Link Extended Default"),
 *   field_types={
 *    "link"
 *   }
 * )
 */
class EnhancedLinkWidget extends LinkWidget {

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    return [
        'max_label_length' => 255,
      ] + parent::defaultSettings();
  }

  /**
   * {@inheritdoc}
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state) {
    $element = parent::formElement($items, $delta, $element, $form, $form_state); // TODO: Change the autogenerated stub

    $element['title']['#maxlength'] = $this->getSetting('max_label_length');

    return $element;
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm(array $form, FormStateInterface $form_state) {
    $elements = parent::settingsForm($form, $form_state);

    $elements['max_label_length'] = [
      '#type' => 'number',
      '#title' => $this->t('Link text maximum length'),
      '#default_value' => $this->getSetting('max_label_length'),
      '#description' => $this->t('The maximum number of characters for the link text. Default is 255.'),
    ];

    return $elements;
  }

  public function settingsSummary() {
    $summary = parent::settingsSummary();
    $summary[] = $this->t("Maximum Link text length: @max_title_length", ['@max_title_length' => $this->getSetting('max_label_length')]);
    return $summary;
  }
}